raw_dataset_path: "/media/nziaei/0884BA9484BA83AA/Datasets/PetCT/raw/"
preprocessed_dataset_path: "/media/nziaei/0884BA9484BA83AA/Datasets/PetCT/preprocessed/"
model_path: "/media/nziaei/0884BA9484BA83AA/projects/PETCTSegmentation/"
