# Dataset name to use : "pilot01" "clear"
dataset: "pet_ct"
data_type: "psma" # "psma" "fdg" "both"
modality: "pet" # "ct", "pet" , "both"

use_negative_samples : False
load_preprocessed_data : True
preprocessing_configs : {
    'scale_ct': {'mode': "normalization", 'min': -1500, 'max': 3500},
    'scale_pet': {'mode': "normalization", 'min': 0, 'max': 120},
    'resample_image': {'target_shape': (200, 200)}
}

slice_spacing: 3
slice_overlap: 0


model: "unet"

# Training LDGD
load_trained_model : False
batch_size : 8
num_epochs : 20
test_size: 0.2
validation_size: 0.1
learning_rate: 0.0001

# Enable or disable debug mode
debug_mode: true

