dataset: "pet_ct"
data_type: "psma" # "psma" "fdg" "both"
use_negative_samples : False
load_preprocessed_data : False

slice_spacing: 3
slice_overlap: 0


model: "unet"

# Training LDGD
load_trained_model : False
batch_size : 4
num_epochs : 5
test_size: 0.2
validation_size: 0.1
learning_rate: 0.0001

# Enable or disable debug mode
debug_mode: true